In [1]:
import numpy as np

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
arr1=np.random.randint(1,100,(3,3))

In [3]:
arr1

array([[68, 73, 18],
       [42, 17, 95],
       [15, 96, 78]])

In [4]:
arr1.T

array([[68, 42, 15],
       [73, 17, 96],
       [18, 95, 78]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [5]:
arr2=np.arange(10)

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
arr2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [9]:
arr3=np.random.rand(4,4)

In [10]:
arr3

array([[0.20789088, 0.94236879, 0.33418499, 0.74804345],
       [0.37646358, 0.20348244, 0.892173  , 0.65450792],
       [0.0870831 , 0.39025593, 0.94906547, 0.32327938],
       [0.51138725, 0.17792632, 0.26980238, 0.01734754]])

In [11]:
arr4=np.zeros((6,6))

In [12]:
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
arr4[1:5, 1:5] = arr3

In [14]:
arr4

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.20789088, 0.94236879, 0.33418499, 0.74804345,
        0.        ],
       [0.        , 0.37646358, 0.20348244, 0.892173  , 0.65450792,
        0.        ],
       [0.        , 0.0870831 , 0.39025593, 0.94906547, 0.32327938,
        0.        ],
       [0.        , 0.51138725, 0.17792632, 0.26980238, 0.01734754,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [15]:
arr_int=np.arange(10,61,5)

In [16]:
arr_int

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [17]:
l=['python', 'numpy', 'pandas']

In [18]:
arr_str=np.array(l)

In [20]:
arr_str

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [22]:
np.char.upper(arr_str)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [23]:
np.char.lower(arr_str)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [24]:
np.char.capitalize(arr_str)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [25]:
np.char.swapcase(arr_str)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [26]:
arr_word=np.array(['python', 'numpy', 'pandas'])

In [27]:
arr_word_space=[' '.join(word) for word in arr_word]

In [28]:
arr_word=np.array(arr_word_space)

In [29]:
arr_word

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [31]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [33]:
arr1

array([[9, 9, 7],
       [3, 8, 8],
       [3, 7, 2]])

In [34]:
arr2

array([[4, 3, 7],
       [1, 2, 3],
       [4, 8, 1]])

In [35]:
arr1+arr2

array([[13, 12, 14],
       [ 4, 10, 11],
       [ 7, 15,  3]])

In [36]:
arr1-arr2

array([[ 5,  6,  0],
       [ 2,  6,  5],
       [-1, -1,  1]])

In [37]:
arr1*arr2

array([[36, 27, 49],
       [ 3, 16, 24],
       [12, 56,  2]])

In [39]:
arr1/arr2

array([[2.25      , 3.        , 1.        ],
       [3.        , 4.        , 2.66666667],
       [0.75      , 0.875     , 2.        ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [40]:
iden_mat=np.eye(5)

In [41]:
iden_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
dio_ele=np.diag(iden_mat)

In [43]:
dio_ele

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [44]:
random_array = np.random.randint(0, 1001, 100)

print("Random Array:")
print(random_array)

def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    max_divisor = int(n**0.5) + 1
    for d in range(3, max_divisor, 2):
        if n % d == 0:
            return False
    return True


prime_numbers = [num for num in random_array if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Array:
[586 616 490 709 510 719  14 161 795   1 560 388  76 449 198 925 205 236
 305 130 367 135 100 704 953 126 406 719 851 919 326 930 456 610 553 314
 800 551 227 406 357  93 588 251 579 761 610  64 699 439 789 250 500 299
 446 518 852 413 347 497 241 449 567 468 686 245   9 741 511  58 241 605
  27 146 257 955 368 276 118  47 960  91 303 931 689 629 673 578 128  81
 844 245 974  70 523 131 911 735 485 910]

Prime Numbers in the Array:
[709, 719, 449, 367, 953, 719, 919, 227, 251, 761, 439, 347, 241, 449, 241, 257, 47, 673, 523, 131, 911]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [45]:
daily_temperatures = np.array([30, 32, 31, 29, 28, 27, 26, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])

weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

for week, avg in enumerate(weekly_averages, start=1):
    print(f"Week {week} average temperature: {avg:.2f}°C")


Week 1 average temperature: 29.00°C
Week 2 average temperature: 33.00°C
Week 3 average temperature: 40.00°C
Week 4 average temperature: 47.00°C
Week 5 average temperature: 51.50°C
